### ISSUE TITLE
support bundle exec if has file Gemfile

### ISSUE THREAD

**Issue by stardiviner** [aaronbieber/octopress-mode#10]
If has `Gemfile` in `octopress/`. I got error same as this: https://github.com/octopress/octopress/issues/115

I hope `octopress.el` can append `bundle exec` if has `Gemfile`.

**Comment by aaronbieber** [comment]
I think that should be straightforward to implement, I'll have a look. I don't run through bundle myself so I'll have to see if I can set it up for testing.

**Comment by stardiviner** [comment]
@aaronbieber thanks

**Comment by stardiviner** [comment]
@aaronbieber command `jekyll serve` also need prefix `bundle exec`. I have added pull request.
https://github.com/aaronbieber/octopress.el/pull/11
