### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [aaronbieber/octopress-mode#12]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by tarsius** [comment]
Friendly ping! Sorry for being pushy, but it looks like rms is going to request that all unlicensed packages be removed from Melpa, and if I can demonstrate that authors are still acting in response to my requests such as this one, then he might delay that another few weeks, giving the remaining authors more time to act. I think it would be a mistake to remove the unlicensed packages as that has the potential of causing a lot of bad blood.

Thanks a lot!

**Comment by aaronbieber** [comment]
I wasn't aware that RMS had any influence over MELPA whatsoever, but I am
happy to add this license to the project, I just haven't had time in the
last couple of weeks since we recently had a baby and I'm not sleeping a
lot.

I will do this, though, thanks for the context.

**Comment by aaronbieber** [comment]
As an additional note, I found the original request to be rather "out of left field," and if you had provided this information about the impact to MELPA and the request from RMS, that would have generated a bit more motivation. Hopefully this helps you get traction with other projects.

**Comment by tarsius** [comment]
> I wasn't aware that RMS had any influence over MELPA whatsoever

He thinks that all Emacs lisp has to use a license that is compatible by the license used by Emacs, and while the Melpa maintainers and many others disagree, they might still comply with his wishes to avoid legal trouble.

> As an additional note, I found the original request to be rather "out of left field," and if you had provided this information about the impact to MELPA and the request from RMS, that would have generated a bit more motivation. Hopefully this helps you get traction with other projects.

Thanks for the feedback. I got a lot of positive feedback after sending out the original request, so it seems that some of the contacted authors appreciated that approach (leave out the politics, focus on how to do it). But others might have felt the similarly to you, and hopefully many of those will react to the updated request as you have.

> we recently had a baby

Congratulations!

**Comment by tarsius** [comment]
Thanks!
