### ISSUE TITLE
add an option to store user octopress blog path, and used for function `octopress-status'

### ISSUE THREAD

**Issue by stardiviner** [aaronbieber/octopress-mode#9]
Everytime input Octopress blog path is hateful, I think octopress.el can specify an option to user blog path, then function `octopress-status` can read it.

**Comment by aaronbieber** [comment]
I will add this. If you trigger the status function while you have a blog
file open in the current buffer, it will find the blog automatically.

**Comment by stardiviner** [comment]
This is a helpful trick, I use workgroups2, it can keep file open path, good. (But a path variable still good)

**Comment by aaronbieber** [comment]
You can now customize `octopress-blog-root` to explicitly set the root; if you do this, you will never be asked for the blog site path, and there is no way to point `octopress` to any other site.
